#!/bin/zsh

current_dir="${PWD##*/}" && target_dir="$(cd .. && pwd)/wav_${current_dir}" && mkdir -p "$target_dir" && for file in *.flac; do printf "Converting: %s ... " "$file"; ffmpeg -loglevel error -stats -i "$file" -map 0:a:0 -map_metadata 0 -c:a pcm_s16le "${target_dir}/${file%.*}.wav"; printf " [DONE]\n"; done && printf "\n🎉 All files converted successfully!\n📂 Output Folder Path: %s\n" "${target_dir}"
